[package]
name = "zero-log"
version = "0.3.0"
edition = "2024"
description = "An ultra-fast, zero-dependency, and zero-allocation log streaming and analysis library for Rust."
license ="MIT"
repository = "https://github.com/dex0o0/zero-log"
readme = "README.md"
keywords = ["logging", "parser", "zero-copy", "performance"]
categories = ["development-tools::debugging", "parsing"]

[dependencies]

[dev-dependencies]
criterion = {version = "0.8.2",features=["html_reports"]}

[[bench]]
name = "log_benchmarks"
harness = false
